### ISSUE TITLE
How to Log to a .txt or .log file?

### ISSUE THREAD

**Issue by Jargon4072** [martinmoene/clue#5]
I want to use this to log to a .txt to .log file. How can I do that?

**Comment by martinmoene** [comment]
Thanks for asking @Jargon4072 .
 
 I see that there's no such example.

Defining `clue_LOG_EXPRESSION` may allow you to setup writing to a file, see [example 3 for using `clue_LOG_EXPRESSION`](https://github.com/martinmoene/clue/blob/master/examples/example3.cpp).

I'll try to think of and add an example later.

Hope this helps.

**Comment by martinmoene** [comment]
@Jargon4072, Trying to add something like `clue_LOG_TO_FILE`. Please don't hold your breath :)

**Comment by martinmoene** [comment]
@Jargon4072 , Added `clue_LOG_TO_FILE`, see [example 5](https://github.com/martinmoene/clue/blob/master/examples/example5.cpp).

**Comment by Jargon4072** [comment]
Thanks a lot! I can now log into a file! Thank you so much for your very fast reply and for adding this feature quickly :) I  am now closing it!!

**Comment by Jargon4072** [comment]
Hi,
I tried your method and I got the below errors: 
![image](https://user-images.githubusercontent.com/15521012/107320482-c5d3e800-6ac6-11eb-80f6-6cd3a3edee80.png)

Also, I tried giving log file name via #define clue_LOG_TO_FILE "clue.txt" in example5.cpp it worked but it was not appending logs at the end of the file instead it replaced the existing lines in the file. How to make it to append new logs at the end instead of replacing exiting lines?

**Comment by martinmoene** [comment]
Yeah i later realized i forgot to open the file for apppend. Will change that.

**Comment by martinmoene** [comment]
> I tried your method and I got the below errors: stray '\\'...

Looks like in your shell the '\\' should be omitted, like:

```Text
g++ -Wall -Wextra -Weffc++ -I.. -Dclue_LOG_TO_FILE="clue-log.txt" -o example5.exe example5.cpp && example5
```

**Comment by Jargon4072** [comment]
Everything is working perfectly. Thanks!! Also, in the multithreaded environment this is working well so far. Thanks a lot!! :)

**Comment by martinmoene** [comment]
Thanks for your question & feedback :)
